### ISSUE TITLE
Caching implementation for files

### ISSUE THREAD

**Issue by adyanth** [rkhwaja/fs.googledrivefs#27]
Is there any form of cache implementation for files?

Something similar to fs.remote or CacheFS?

It would really be helpful to cache the files (probably using some algorithms such as LRU) because each call to access a file (especially small files like images and such) would call an API which is really slow.

**Comment by rkhwaja** [comment]
I used to have caching at the http client level when I used httplib2 as the http library - it involved specifying a directory to cache the http responses. Since I had to switch to google-auth, I'm not sure which http client library it's using under the covers (possibly requests?), but I'm not specifying a cache directory anymore so I don't see how it could be caching.

You can see at https://github.com/googleapis/google-api-python-client/blob/master/docs/performance.md how they recommend that you cache the API responses.

**Comment by adyanth** [comment]
Oh that is some good info from the link you sent. They are also using httplib2 I think.

My idea in this issue was to check something on the file/filesystem level caching, like once the file is downloaded, cache the file locally, and serve the same based on if the file is dirty locally or was modified remotely based on its metadata.

**Comment by rkhwaja** [comment]
I think that the only way to tell whether your cached file data is valid is through the standard http cache control stuff, which means figuring out what's happening with their http client library under the hood.

If you wanted to assume that you're the only client, you could do some client-side caching using that fs.remote-type method.

There's also the possibility of using the sync support that they have (e.g. https://developers.google.com/drive/api/v3/push) to keep an up-to-date local cache, but that would be pretty complicated to get right.

**Comment by rkhwaja** [comment]
For single client client-side caching, someone should implement a wrapping filesystem which does this.
